package inference

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"iter"

	"github.com/honganh1206/clue/message"
	"github.com/honganh1206/clue/prompts"
	"github.com/honganh1206/clue/schema"
	"github.com/honganh1206/clue/tools"
	"google.golang.org/genai"
)

type GeminiClient struct {
	BaseLLMClient
	client    *genai.Client
	model     ModelVersion
	maxTokens int64
	contents  []*genai.Content
	tools     []*genai.Tool
	// TODO: field for caching
}

func NewGeminiClient(client *genai.Client, model ModelVersion, maxTokens int64) *GeminiClient {
	return &GeminiClient{
		client:    client,
		model:     model,
		maxTokens: maxTokens,
	}
}

func (c *GeminiClient) ProviderName() string {
	return c.BaseLLMClient.Provider
}

func getGeminiModelName(model ModelVersion) string {
	return string(model)
}

func (c *GeminiClient) SummarizeHistory(history []*message.Message, threshold int) []*message.Message {
	return c.BaseLLMClient.BaseSummarizeHistory(history, threshold)
}

func (c *GeminiClient) TruncateMessage(msg *message.Message, threshold int) *message.Message {
	return c.BaseLLMClient.BaseTruncateMessage(msg, threshold)
}
func (c *GeminiClient) RunInferenceStream(ctx context.Context) (*message.Message, error) {
	if len(c.contents) == 0 {
		return nil, errors.New("gemini: no messages in conversation history")
	}

	modelName := getGeminiModelName(c.model)

	sysPrompt := prompts.GeminiSystemPrompt()

	config := &genai.GenerateContentConfig{
		MaxOutputTokens:   int32(c.maxTokens),
		Tools:             c.tools,
		SystemInstruction: genai.NewContentFromText(sysPrompt, genai.RoleUser),
	}

	iter := c.client.Models.GenerateContentStream(ctx, modelName, c.contents, config)

	response, err := streamGeminiResponse(iter)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (c *GeminiClient) ToNativeHistory(history []*message.Message) error {
	if len(history) == 0 {
		return errors.New("gemini: empty conversation history")
	}
	c.contents = make([]*genai.Content, 0, len(history))

	for _, msg := range history {
		if err := c.ToNativeMessage(msg); err != nil {
			return err
		}
	}

	return nil
}

func (c *GeminiClient) ToNativeMessage(msg *message.Message) error {
	if msg == nil {
		return errors.New("gemini: message is nil")
	}

	parts := convertToGeminiParts(msg.Content)
	if len(parts) == 0 {
		return errors.New("gemini: message has no content parts")
	}

	content := &genai.Content{
		Role:  msg.Role,
		Parts: parts,
	}

	c.contents = append(c.contents, content)
	return nil
}

func (c *GeminiClient) ToNativeTools(tools []*tools.ToolDefinition) error {
	if len(tools) == 0 {
		return errors.New("gemini: no tools provided")
	}

	builtinTool := &genai.Tool{
		FunctionDeclarations: make([]*genai.FunctionDeclaration, 0, len(tools)),
	}

	for _, tool := range tools {
		geminiToolFuncDec, err := convertToGeminiFunctionDeclaration(tool)
		if err != nil {
			return err
		}
		builtinTool.FunctionDeclarations = append(builtinTool.FunctionDeclarations, geminiToolFuncDec)
	}

	c.tools = []*genai.Tool{builtinTool}

	return nil
}

func streamGeminiResponse(response iter.Seq2[*genai.GenerateContentResponse, error]) (*message.Message, error) {
	var fullText string
	var toolCalls []message.ContentBlock
	var outputContents []*genai.Content

	msg := &message.Message{
		Role:    message.ModelRole,
		Content: make([]message.ContentBlock, 0),
	}

	for chunk, err := range response {
		if err == io.EOF {
			break
		}

		if err != nil {
			return nil, err
		}

		// A candidate contains a content,
		// a content contains one or more parts
		if len(chunk.Candidates) == 0 || chunk.Candidates[0].Content == nil {
			return nil, fmt.Errorf("no content returned")
		}

		// First candidate is the most relevant response generated by the model,
		// so we only record the first candidate's content as the best one
		bestCandidate := chunk.Candidates[0]
		bestContent := bestCandidate.Content

		// If no parts, check if this is a completion signal
		if len(bestContent.Parts) == 0 {
			if bestCandidate.FinishReason != "" {
				// TODO: We have a max length limit of 1024
				// so if the content exceeds 1024 the fetch MCP tool would stop
				// and there will be a finish reason
				fmt.Printf("finish reason indicates: %v\n", chunk.Candidates[0].FinishReason)
				// Continue to next chunk instead of processing empty parts
				outputContents = append(outputContents, bestContent)
				continue
			}
		}

		for _, p := range bestContent.Parts {
			if p.Text != "" {
				fmt.Print(p.Text)
				fullText += p.Text
			}
			if p.FunctionCall != nil {
				fc := p.FunctionCall
				inputBytes, err := json.Marshal(fc.Args)
				if err != nil {
					return nil, fmt.Errorf("failed to marshal function args: %w", err)
				}

				toolCall := message.NewToolUseBlock(
					fc.ID,
					fc.Name,
					inputBytes,
				)
				toolCalls = append(toolCalls, toolCall)
			}
		}

		outputContents = append(outputContents, bestContent)
	}

	if fullText != "" {
		msg.Content = append(msg.Content, message.NewTextBlock(fullText))
	}

	msg.Content = append(msg.Content, toolCalls...)
	fmt.Println()

	return msg, nil
}

func convertToGeminiParts(blocks []message.ContentBlock) []*genai.Part {
	parts := make([]*genai.Part, 0, len(blocks))

	for _, b := range blocks {
		switch b.Type() {
		case message.TextType:
			if textBlock, ok := b.(message.TextBlock); ok {
				parts = append(parts, genai.NewPartFromText(textBlock.Text))
			}
		case message.ToolUseType:
			if toolUse, ok := b.(message.ToolUseBlock); ok {
				var args map[string]any

				err := json.Unmarshal(toolUse.Input, &args)
				if err != nil {
					continue
				}

				parts = append(parts, genai.NewPartFromFunctionCall(toolUse.Name, args))
			}
		case message.ToolResultType:
			if toolResult, ok := b.(message.ToolResultBlock); ok {
				// Gemini NEEDS the content to be wrapped inside "result"
				response := map[string]any{"result": toolResult.Content}

				parts = append(parts, genai.NewPartFromFunctionResponse(toolResult.ToolName, response))
			}
		}
	}

	return parts
}

func convertToGeminiTools(tools []*tools.ToolDefinition) ([]*genai.Tool, error) {
	if len(tools) == 0 {
		return nil, nil
	}

	builtinTool := &genai.Tool{
		FunctionDeclarations: make([]*genai.FunctionDeclaration, 0, len(tools)),
	}

	for _, tool := range tools {
		geminiToolFuncDec, err := convertToGeminiFunctionDeclaration(tool)
		if err != nil {
			return nil, err
		}
		builtinTool.FunctionDeclarations = append(builtinTool.FunctionDeclarations, geminiToolFuncDec)
	}

	return []*genai.Tool{builtinTool}, nil
}

func convertToGeminiFunctionDeclaration(tool *tools.ToolDefinition) (*genai.FunctionDeclaration, error) {
	params, err := schema.ConvertToGeminiSchema(tool.InputSchema)
	if err != nil {
		return nil, fmt.Errorf("failed to convert schema to Gemini format: %w", err)
	}

	functionDecl := &genai.FunctionDeclaration{
		Name:        tool.Name,
		Description: tool.Description,
		Parameters:  params,
	}

	return functionDecl, nil
}
